const STORE_REFIX = 'TODO_';

export const SET_TODO_LIST = `${STORE_REFIX}SET_TODO_LIST`;
export const SET_FILTER_VALUE = `${STORE_REFIX}SET_FILTER_VALUE`;
export const UPDATE_TODO = `${STORE_REFIX}UPDATE_TODO`;
export const TOGGLE_SELECT_ALL = `${STORE_REFIX}TOGGLE_SELECT_ALL`;
export const DELETE_TASK = `${STORE_REFIX}DELETE_TASK`;
export const CHANGE_TASK_STATUS = `${STORE_REFIX}CHANGE_TASK_STATUS`;
export const CLEAR_COMPLETED_TASKS = `${STORE_REFIX}CLEAR_COMPLETED_TASKS`;